### ISSUE TITLE
Left margin not consistent within a section when using detailed_entries or brief_entries

### ISSUE THREAD

**Issue by wittja01** [mitchelloharawild/vitae#145] opened 2020-11-23 15:50 UTC
When I use `tribble()` with the `deatiled_entries()` or `brief_entries()` function, the first item in each section has a margin that is one increment closer to the left side of the page. I've attached a screenshot of what I mean since I'm not sure of the exact language to describe the issue. You can see the first entry for the "President's Prize" looks like it's one "unit" closer to the left side than the entries below it. 

Unfortunately, I'm not sure how to reproduce the issue. I opened a new template file based on the awesome-cv and knit that. There was no issue with the margin there. I did edit the awesome-cv.cls file a year ago to change some things (haven't had to update my CV since then), I'm wondering if I possibly introduced something there that would cause this? I'm using version 0.3.0 of vitae.

![left_margin](https://user-images.githubusercontent.com/13739421/99983071-072ee400-2d71-11eb-9948-614db1dc1caf.png)

**Comment by mitchelloharawild** [comment] 2021-01-10 00:59
I am unable to reproduce this issue, although I do recall this being an issue fixed in awesome-cv.cls before.

Perhaps you could go through the history of the files and see what differs: https://github.com/mitchelloharawild/vitae/commits/ade4e02d5af7efefd145fd670bfa74a0e73bc3e6/inst/rmarkdown/templates/awesomecv/skeleton/awesome-cv.cls

--- 
`cv.rmd`

````
---
name: vitae
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: CRAN
position: package
address: GitHub
github: mitchelloharawild
twitter: "mitchoharawild"
headcolor: 414141
output: 
  vitae::awesomecv:
    keep_tex: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

```{r}
dt <- tibble::tibble(what = paste("what", 1:3), when = "when", with = "with", where = "where", why = "why")
detailed_entries(dt, what, when, with, where, why)
brief_entries(dt, what, when, with)
```


````

![image](https://user-images.githubusercontent.com/16127127/104111813-eaf40000-533a-11eb-8ffa-ccb5ffed2a7e.png)

**Closed** 2021-01-15 03:36 UTC
Labels: invalid
