### ISSUE TITLE
Awesome - CV: Gitlab and Research gate profile icon

### ISSUE THREAD

**Issue by matthieugold** [mitchelloharawild/vitae#115] opened 2020-04-19 17:35 UTC
Hi,

Is it possible to add a gitlab and researchgate profile icon in Awesome CV? (like the github/linkedin).

Thanks! :)

Matthieu

**Comment by mitchelloharawild** [comment] 2020-04-21 23:45
Hi Matthieu,

It is not currently possible to add these into awesome CV. There are plans to generalise this functionality to support any icon, as discussed here: https://github.com/mitchelloharawild/vitae/issues/69

**Comment by mitchelloharawild** [comment] 2020-05-01 03:02
Closing as duplicate of #69

**Closed by mitchelloharawild** 2020-05-01 03:02 UTC

**Comment by ntrlshrp** [comment] 2020-12-14 15:12
At [line 98](https://github.com/mitchelloharawild/vitae/blob/c7a73d12f8d553c39f837ef4a79844f253eaa847/inst/rmarkdown/templates/awesomecv/resources/awesome-cv.tex#L98) of `templates/awesomecv/resources/awesome-cv.tex`, I [just added](https://github.com/ntrlshrp/vitae/commit/8eb976eee0a2b0da742be3d729dd63e0eeaa9a7c):

```
$if(gitlab)$
\gitlab{$gitlab$}
$endif$
```

Then I rebuilt the package and added `gitlab: mariecurie` to the YAML header of the `templates/awesomecv/skeleton/skeleton.Rmd` and made the attached [skeleton.pdf](https://github.com/mitchelloharawild/vitae/files/5689609/skeleton.pdf).

**Comment by nuest** [comment] 2021-04-28 17:17
I also did this in my fork now - I understand the usefulness of a generic support, but it would be great to just include these three (!) lines and support GitLab until #69 is completed.
