### ISSUE TITLE
bibliography_entries() propblems on missing "\item" for every publication list (bug)

### ISSUE THREAD

**Issue by byronchu77** [mitchelloharawild/vitae#251] opened 2024-03-14 20:53 UTC
There is a now in the bibliography_entries() function, which is likely due to a missing "\item" for the lists of publications. 
I use the template of Hyndman to test this, the error message comes as  "! LaTeX Error: Something's wrong--perhaps a missing \item."
When I checked the .tex file, and found the problem lies in these code:
```\hypertarget{publications}{%
\section{Publications}\label{publications}}

\hypertarget{refs-9ab79af7a94489e94e6182750a67b967}{}
\begin{CSLReferences}{0}{0}
\leavevmode\vadjust pre{\hypertarget{ref-R-vitae}{}}%
\CSLLeftMargin{1. }%
\CSLRightInline{O'Hara-Wild, M., \& Hyndman, R. (2023). \emph{Vitae:
Curriculum vitae for r markdown}.
\url{https://pkg.mitchelloharawild.com/vitae/}}

\leavevmode\vadjust pre{\hypertarget{ref-R-tibble}{}}%
\CSLLeftMargin{2. }%
\CSLRightInline{Müller, K., \& Wickham, H. (2023). \emph{Tibble: Simple
data frames}. \url{https://tibble.tidyverse.org/}}

\end{CSLReferences}
```
I tried to insert an "\item" in front of each list, and it worked.
 
```LaTex 
\begin{CSLReferences}{0}{0}
    \item \leavevmode\vadjust pre{\hypertarget{ref-R-vitae}{}}%
        \CSLLeftMargin{1. }%
        \CSLRightInline{O'Hara-Wild, M., \& Hyndman, R. (2023). \emph{Vitae: Curriculum vitae for r markdown}. \url{https://pkg.mitchelloharawild.com/vitae/}}
    
    \item \leavevmode\vadjust pre{\hypertarget{ref-R-tibble}{}}%
        \CSLLeftMargin{2. }%
        \CSLRightInline{Müller, K., \& Wickham, H. (2023). \emph{Tibble: Simple data frames}. \url{https://tibble.tidyverse.org/}}
\end{CSLReferences}
```
 I figured it because the function, "bibliography_entries()", needed to be updated since I did not have this problem one month ago. The issue might be due to the recent update in R or latex itself. 

Thank you.

**Comment by XinweiBuffalo** [comment] 2024-03-16 16:19
Same issue. Finally find a solution! Thanks

**Comment by the-tave** [comment] 2024-04-23 14:58
Thanks for describing this issue! I kept getting an Error saying "! LaTeX Error: Something's wrong--perhaps a missing \item." and I couldn't figure it out. Is there a possible work-around directly in the Rmd file? Or maybe a patch coming up?
Cheers

**Comment by plbaldoni** [comment] 2024-05-19 03:25
I am experiencing the same issue

**Comment by jdtonkin** [comment] 2024-05-28 08:47
Same here

**Comment by mitchelloharawild** [comment] 2024-05-28 11:23
This is discussed further in #246, I believe it is a pandoc versioning issue. Any fixes which work with all versions of pandoc are welcomed.

**Comment by mitchelloharawild** [comment] 2024-06-12 17:56
Closing as duplicate of #246

**Closed by mitchelloharawild** 2024-06-12 17:56 UTC
