### ISSUE TITLE
Special characters read from .xlsx or .csv files not rendered correctly

### ISSUE THREAD

**Issue by CarlosPoses** [mitchelloharawild/vitae#180] opened 2021-09-06 12:24 UTC
I am trying to create an entry with some projects' information based on an Excel file in which I have stored information about these projects. Some projects have a Spanish name and thus use some special characters (like : á). When I knit the document, these are rendered incorrectly.
![image](https://user-images.githubusercontent.com/85176234/132215584-55af67d8-9ecc-4f7f-ab19-cf98408aa004.png)
But the behavior is not the same if instead of reading the files from an excel file I create a tibble in the code itself, using the exact same names.
![image](https://user-images.githubusercontent.com/85176234/132215668-d29adde0-0811-4e39-bfd4-697145467f29.png)

See code below, and excel file attached.
[repex.xlsx](https://github.com/mitchelloharawild/vitae/files/7115915/repex.xlsx)

````
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readxl)
library(tidyverse)
```

# Projects

```{r}

projects_tibble <- tibble(
  title = "Política y Economía",
  role = "Researcher",
  year = 2012
)

projects_tibble %>% 
  detailed_entries(
    what = title,
    with = role,
    when = year)

projects_excel <- readxl::read_excel("repex.xlsx")

projects_excel %>% 
  detailed_entries(
    what = title,
    with = role,
    when = year)

```
````

When knitted, projects_tibble works as expected, but projects_excel does not. Seems related to #158 and #167 , but this is not for .bib files but for .xlsx files. I would say the issue is not fixed for these kind of files? I tried but got the same problem using .csv files instead of an .xlsx file. Also converting the projects_excel to a tibble once read did not seem to work either.

**Comment by mitchelloharawild** [comment] 2021-09-14 05:11
I'm unable to reproduce this issue. 
![image](https://user-images.githubusercontent.com/16127127/133197866-4bff5a88-02c5-498f-942d-0df43c21a3f1.png)

Are you using Windows? It is likely an encoding related problem upstream in the `readxl` package. Could you try installing the dev version of `readxl`, and see if `projects_tibble` and `projects_excel` differ in a meaningful way? You can use `waldo::compare(projects_tibble, projects_excel)` to compare the results.

**Comment by CarlosPoses** [comment] 2021-09-14 08:29
Hi,

Thanks a lot for your help! I am using Windows indeed. I have done as suggested as this is what I get:

![image](https://user-images.githubusercontent.com/85176234/133222340-b2fb7634-a9cd-4b18-abdd-cd8e1b153736.png)

It seems the issue is in the backslash - but not sure what to make about it. I tried reading the excel file with openxlsx instead. It did not solve the issue. I get this:
![image](https://user-images.githubusercontent.com/85176234/133223337-ed1c191b-3971-460d-97da-841c05fd718b.png)

Seems the issue is the backslash again. Do you know if there's something that can be done about this?

Best,

Carlos

**Comment by mitchelloharawild** [comment] 2021-12-06 04:11
Closing as this is not an issue that can/should be fixed in `{vitae}`. The problem relates to the method used to import the data (using `{readxl}`) and not how `{vitae}` handles the provided data.

**Closed by mitchelloharawild** 2021-12-06 04:11 UTC
